
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
target 'WDMap' do
  use_frameworks!
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'SDWebImageFLPlugin'
  pod 'MJExtension'
  pod 'MJRefresh'
#  pod 'Tencent-MapSDK'
  pod 'ZKCycleScrollView'
  pod 'FLAnimatedImage'
  pod 'SDCycleScrollView'
end

